scripts:
  - /assets/js/warmonger-miniatures.js
stylesheets:
  - /assets/css/warmonger-miniatures.css
author: David Susco
title: Warmonger Miniatures

# Where things are
source: _site
destination: public_html
sass:
  style: compressed

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: page
  -
    scope:
      path: assets
    values:
      layout: none

# Theme
theme: baseline
