author: David Susco
description: The home of high-quality, 10mm fantasy and historical minis.
scripts:
  - https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/jquery.touchswipe/1.6.19/jquery.touchSwipe.min.js
stylesheets:
  - https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
tagline: 10mm for the Aspiring Warmaster
title: Warmonger Miniatures

# Where things are
source: _site
destination: public_html
collections:
  posts:
    permalink: news/:year/:month/:title:output_ext
  products:
    output: true
    permalink: store/:path:output_ext
sass:
  style: compressed

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: page
  -
    scope:
      type: posts
    values:
      author: Dave
      layout: post
  -
    scope:
      type: products
    values:
      layout: product
  -
    scope:
      path: news
      type: pages
    values:
      breadcrumb_template: '%{date}'
      description_template: 'Warmonger Miniatures %{full_date} news posts.'
      heading_template: 'Warmonger Miniatures %{full_date} News'
      paginate: 5
      title_template: '%{full_date} News'
  -
    scope:
      path: news/tags
      type: pages
    values:
      breadcrumb_template: '%{tag}'
      description_template: 'Warmonger Miniatures %{tag} news posts.'
      heading_template: 'Warmonger Miniatures %{tag} News'
      title_template: '%{tag} News'
  -
    scope:
      path: store/index.html
    values:
      description: The place to buy all of Warmonger Miniatures' 10mm fantasy and historical miniatures.
      heading: Warmonger Miniatures Store
  -
    scope:
      path: store/10mm-landsknechte/index.html
    values:
      description: Warmonger Miniatures' line of 10mm Landsknecht and 16th century German miniatures.
      image: warmonger-miniatures.com/store/10mm-landsknechte/ls01/ls01
  -
    scope:
      path: store/10mm-polish-lithuanian/index.html
    values:
      description: Warmonger Miniatures' line of 10mm Polish-Lithuanian miniatures.
      image: warmonger-miniatures.com/store/10mm-polish-lithuanian/pl01/pl01a
      title: 10mm Polish-Lithuanian
  -
    scope:
      path: store/10mm-fantasy/index.html
    values:
      description: Warmonger Miniatures' line of 10mm Fantasy miniatures.
      image: warmonger-miniatures.com/store/10mm-fantasy/fn01/fn01
      title: 10mm Fantasy
  -
    scope:
      path: store/10mm-safavid/index.html
    values:
      description: Warmonger Miniatures' line of 10mm Safavid miniatures.
      image: warmonger-miniatures.com/store/10mm-safavid/sv01/sv01a
      title: 10mm Safavid
  -
    scope:
      path: store/bases-and-accessories/index.html
    values:
      description: Warmonger Miniatures' line of laser cut bases and accessories.
      image: warmonger-miniatures.com/store/bases-and-accessories/b1.5bx20x40-3
  -
    scope:
      path: store/preorders/index.html
    values:
      description: Warmonger Miniatures' Preorders.
      image: warmonger-miniatures.com/news/winged-hussar-wip
